# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello_gha:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.7.0
      - name: Run a multi-line script
        run: |
          cl /EHsc main.cpp
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: main.exe
          retention-days: 10
  telegram:
      runs-on: ubuntu-latest
      needs: hello_gha
      steps:
        - name: getArtifact
          uses: actions/download-artifact@v2
          with:
             name: artifact
        - name: send message
          uses: appleboy/telegram-action@master
          with:
            to: 379230514
            token: 1747226005:AAHQ32qjCEJpZMurDVSlPLyDZztSrjYHCBw
            message: The ${{ github.event_name }} event triggered final step.
            document: main.exe
